### ISSUE TITLE
Add support for non-numerical font-weight values

### ISSUE THREAD

**Issue by sixhours** [signal-noise/stylelint-scales#37]
> What is the problem you're trying to solve?

👋 Hello! We need to be able to use non-numerical values for `font-weight`s, such as `inherit`, `normal`, or `bold`.

> What solution would you like to see?

The ability to provide an array to stylelintrc that looks like `[ 400, 700, "normal", "bold", "inherit" ]`, with mixed number and string values.

Removing the `Number` function here works in my initial tests:
https://github.com/signal-noise/stylelint-scales/blob/master/lib/rules/font-weight/index.js#L40

Ideally, I'd check against an array of [valid CSS values for font-weight](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight) in addition to the user-given array in stylelintrc.

Thanks for your time!

**Comment by digitaljohn** [comment]
@sixhours Thanks for reporting this... we will get this resolved asap.
