### ISSUE TITLE
Show units in addition to values for clarity

### ISSUE THREAD

**Issue by sixhours** [signal-noise/stylelint-scales#42]
> What is the problem you're trying to solve?

It would be helpful to include the unit when showing an error for font size values that differ from the accepted array.

Right now, the unit is only noted if it's the only thing that's incorrect; in this example, the font size is `18px`, but should be in `rem`s. The error only specifies the array of values:

<img width="523" alt="88706464-e619f780-d0de-11ea-9cd5-7633c9393b33" src="https://user-images.githubusercontent.com/2124984/90158782-730ab500-dd5d-11ea-9b26-1ea9bd064834.png">

Devs/designers need to guess or hunt for the correct unit before correcting the error.

> What solution would you like to see?

Tacking on a "with {unit}s" to the returned error message:

"Expected 32px to be one of "0.75, 1.0" with unit "rem, em""

Or returning separate errors for values and units:

"Expected 32 to be one of "0.75, 1.0""
"Expected px to be one of "rem, em""

Thanks for having a look!

**Comment by digitaljohn** [comment]
@sixhours please check PR #43 

This adds units to the output on all relevant rules not just font-size.

**Comment by digitaljohn** [comment]
@sixhours 1.4.0 released with this change.
