### ISSUE TITLE
Bump package depedencies

### ISSUE THREAD

**Issue by sallynorthmore** [signal-noise/stylelint-scales#58]
> What is the problem you're trying to solve?

There are high vulnerabilities in the package dependencies

![image](https://user-images.githubusercontent.com/981143/106914811-49738a80-66fd-11eb-8780-abe98d16a82f.png)

> What solution would you like to see?

Update the package deps and release

**Comment by sallynorthmore** [comment]
Please 😄

**Comment by jeddy3** [comment]
Hi Sally 👋 

The deps were bumped in https://github.com/signal-noise/stylelint-scales/pull/51, and we'll hopefully have a release out early next week. It'll be a `2.0.0` release as exciting changes are coming, including the [automatic fixing of numeric scales](https://github.com/signal-noise/stylelint-scales/pull/57)!

There are a couple more breaking changes to roll into the `2.0.0`, hence the wait until Monday. As this package is only used in development, those vulnerabilities won't impact on any users. They are unsightly, though 😆

**Comment by jeddy3** [comment]
@sallynorthmore If you want a sneak peek at `2.0.0` you can try the following locally:

```
npm install signal-noise/stylelint-scales#add-autofix --save-dev 
```

It'll be good to know if you run into any issues with your codebase, as `2.0.0` significantly changes the internals of quite a few of the rules.

You'll need to slightly adjust your config for it to work as units will be specified in `2.0.0`. For example:

This pre-2.0.0 config:

```json
{
  "plugins": ["@signal-noise/stylelint-scales"],
  "rules": {
    "scales/font-size": [[4, 10]]
  }
}
```

Will need to become:

```js
{
  "plugins": ["@signal-noise/stylelint-scales"],
  "rules": {
    "scales/space": [
      { "scale": [4, 10], "units": ["px"] },
    ],
  }
}
```

Where the rules now accept an array of objects, each specifying a scale and an array of units.

**Comment by sallynorthmore** [comment]
Awesome, looking forward to the updates  @jeddy3  😍
