### ISSUE TITLE
Add disableFix to scales/font-weights

### ISSUE THREAD

**Issue by siarheiyelin** [signal-noise/stylelint-scales#71]
> What is the problem you're trying to solve?

Disable auto-fix for "scales/font-weights" rule. However the similar feature would be useful for other rules from this lib as well. The main reason is that auto-fix makes potentially breaking changes to the app functionality. E.g. when next rule is defined:
 'scales/font-weights': [100, 300, 400, 500, 700]
And auto-fix is applied, then it's not always safe to replace font-weight to closest value from the list. I would prefer to fix it manually, because it either may require updating other CSS as well to make it work correctly. Or it may require updating list of allowed values.

> What solution would you like to see?

Add some option like in the example below to all rules which make potentially breaking changes, e.g.:
 'scales/font-weights': { [100, 300, 400, 500, 700], {
   disableAutoFix: true,
}]

**Comment by jeddy3** [comment]
Thanks for the request, for using the template and for writing up your use case clearly.

We can add a `disableFix` secondary option, as [recommended in the writing plugin guidelines](https://stylelint.io/developer-guide/plugins#the-anatomy-of-a-plugin).

I know [stylelint-order](https://github.com/hudochenkov/stylelint-order/) has this option: example [code](
https://github.com/hudochenkov/stylelint-order/blob/d1c8d91c8389fa30c159a3bb3c85c965cfcf1e53/rules/properties-alphabetical-order/index.js#L12-L40), [tests](https://github.com/hudochenkov/stylelint-order/blob/d1c8d91c8389fa30c159a3bb3c85c965cfcf1e53/rules/properties-alphabetical-order/tests/index.js#L144-L177) and [docs](https://github.com/hudochenkov/stylelint-order/tree/d1c8d91c8389fa30c159a3bb3c85c965cfcf1e53/rules/properties-alphabetical-order#optional-secondary-options).

We should be able to use default parameters, i.e.:

```js
const rule = (primary, secondary = { disableFix: false }, { fix }) => {
 ..
  if (
      !validateOptions(result, ruleName, {
        actual: primary,
        possible: hasNumericScale,
      },
      {
        actual: secondary,
        possible: {
          disableFix: Boolean,
        },
        optional: true,
      })
    )
      return;
   ..
   if (fix && !disableFix) { .. }
}

```

Would you like to contribute a pull request for this?

**Comment by vmohir** [comment]
The `disableFix` option should be available for all rules. In our use case, we just want to have a warning and fix them manually.

**Comment by jeddy3** [comment]
We [recently added a `disableFix` option to stylelint itself](https://github.com/stylelint/stylelint/pull/5460) which will work for rules in plugins too.

It'll be available in the [next major release of stylelint](https://github.com/stylelint/stylelint/issues/5205).
