### ISSUE TITLE
Add additional scales

### ISSUE THREAD

**Issue by jeddy3** [signal-noise/stylelint-scales#8]
The linter currently supports [5 scales](https://github.com/signal-noise/stylelint-scales#list-of-rules):
- font sizes
- space
- line heights
- font weights
- colours

These are based on the [keys of the theme specification from styled-system](https://styled-system.com/theme-specification#key-reference).

From that list, it'd be great if this plugin pack also supported scales for:

- [x] letter spacings
- [x] word spacings ?
- [x] ~~sizes~~
- [x] fonts
- [x] radii

**Comment by digitaljohn** [comment]
@jeddy3 I believe adding a rule for sizes (width/height etc) will be too restrictive and developers ultimately not use it?

**Comment by digitaljohn** [comment]
#24 closes this.
